name: dev_util
description: A Flutter dev_util package project (仅自使用.ing).
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

flutter_intl:
  enabled: true
  main_locale: zh

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.14.11  
  intl:
  intl_translation:  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2  
  ## 📆选择
  date_range_picker: ^1.0.6  
  # https://github.com/a14n/dart-decimal
  decimal: ">=0.3.1 <2.0.0"
  # https://github.com/dart-lang/crypto
  crypto: ">=2.0.6 <4.0.0"
  # https://github.com/dart-lang/convert
  convert: ">=1.0.0 <4.0.0"

  # dartx: ^0.4.1

  # flutter_screenutil: ^3.2.0
  # flutter_screenutil: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # analysis_options.yaml   https://github.com/dart-lang/pedantic.git
  pedantic: ^1.9.0  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
